int loginProcedure(int, char**);
int lobbyInterpreter(int, char*, char **);
int roomInterpreter(int, char*, char*, int*, int*, int*, int*);
void gameInterpreter(int, char*, char*, int*, int*, int*, int);
char** parseHelper(char*, char*);
void welcomePrint();
void helpPrintLobby();
void helpPrintRoom();
void lobbyPrint(char*);
void joinedPrint(char*);